SinderPhoto/Models/ErrorViewModel.cs
using System;

namespace SinderPhoto.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SinderPhoto/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace SniderPhoto.Controllers
{
    public class AlbumController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Landscapes()
        {
            return View();
        }

        public IActionResult RealEstate()
        {
            return View();
        }

        public IActionResult Portraits()
        {
            return View();
        }
    }
}

SinderPhoto/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SinderPhoto.Models;

namespace SinderPhoto.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Portfolio()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SinderPhoto/Views/Album/Landscapes.cshtml
@{
    ViewData["Title"] = "Landscapes";
}
<h1>@ViewData["Title"]</h1>

<div class="container" id="ladscapeImageGrid">
    <div class="container" id="firstBox">
        <div class="row" id="rowOne">
            <div class="col">
                <img class="img-fluid" src="~/landscape_pics/colorfulLeaves.jpg" alt="">
            </div>
            <div class="col">
                <img class="img-fluid" src="~/landscape_pics/FMBridge.jpg" alt="">
            </div>
            <div class="col">
                <img class="img-fluid" src="~/landscape_pics/forestHillside.jpg" alt="">
            </div>
        </div>
    </div>
    <div class="container" id="secondBox">
        <div class="row" id="rowTwo">
            <div class="col">
                <img class="d-block w-100" src="~/landscape_pics/gazeeboNight1.jpg" alt="">
            </div>
            <div class="col">
                <img class="d-block w-100" src="~/landscape_pics/gazeeboNight2.jpg" alt="">
            </div>
            <div class="col">
                <img class="d-block w-100" src="~/landscape_pics/nightSky.jpg" alt="">
            </div>
        </div>
    </div>
    <div class="container" id="thirdBox">
        <div class="row" id="rowThree">
            <div class="col">
                <img class="d-block w-100" src="~/landscape_pics/stormWithRainbow.jpg" alt="">
            </div>
            <div class="col">
                <img class="d-block w-100" src="~/landscape_pics/sunsetOverWater.jpg" alt="">
            </div>
            <div class="col">
                <img class="d-block w-100" src="~/landscape_pics/SurfAndSky.jpg" alt="">
            </div>
        </div>
    </div>
</div>

SinderPhoto/Views/Album/Portraits.cshtml
@{
    ViewData["Title"] = "Portraits";
}
<h1>@ViewData["Title"]</h1>

<p>Home for Portrait photos</p>
<div class="container" id="portraitImageGrid">
    <div class="row" id="rowOne">
        <div class="col">
            First Image Row One
        </div>
        <div class="col">
            Second Image Row One
        </div>
        <div class="col">
            Third Image Row One
        </div>
    </div>
    <div class="row" id="rowTwo">
        <div class="col">
            First Image Row Two
        </div>
        <div class="col">
            Second Image Row Two
        </div>
        <div class="col">
            Third Image Row Two
        </div>
    </div>
    <div class="row" id="rowThree">
        <div class="col">
            First Image Row Three
        </div>
        <div class="col">
            Second Image Row Three
        </div>
        <div class="col">
            Third Image Row Three
        </div>
    </div>
</div>

SinderPhoto/Views/Album/RealEstate.cshtml
@{
    ViewData["Title"] = "Real Estate";
}
<h1>@ViewData["Title"]</h1>

<p>Home for Real Estate photos</p>
<div class="container" id="realEstateImageGrid">
    <div class="container" id="firstBox">
        <div class="row" id="rowOne">
            <div class="col">
                <img class="img-fluid" src="~/real_estate_pics/bedroom.jpg" alt="">
            </div>
            <div class="col">
                <img class="img-fluid" src="~/real_estate_pics/bikeShop.jpg" alt="">
            </div>
            <div class="col">
                <img class="img-fluid" src="~/real_estate_pics/diningRoom.jpg" alt="">
            </div>
        </div>
    </div>
    <div class="container" id="secondBox">
        <div class="row" id="rowTwo">
            <div class="col">
                <img class="img-fluid" src="~/real_estate_pics/livingroom1.jpg" alt="">
            </div>
            <div class="col">
                <img class="img-fluid" src="~/real_estate_pics/linvingroom2.jpg" alt="">
            </div>
            <div class="col">
                <img class="img-fluid" src="~/real_estate_pics/poolHouse.jpg" alt="">
            </div>
        </div>
    </div>
    <div class="row" id="rowThree">
        <div class="col">
            <img class="img-fluid" src="~/real_estate_pics/rusticStreet.jpg" alt="">
        </div>
        <div class="col">
            <img class="img-fluid" src="~/real_estate_pics/slatersDiningRoom.jpg" alt="">
        </div>
        <div class="col">
            <img class="img-fluid" src="~/real_estate_pics/treeLinedStree.jpg" alt="">
        </div>
    </div>
</div>

SinderPhoto/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h1>@ViewData["Title"]</h1>

<p>About page for RJ Sinder.</p>

SinderPhoto/Views/Home/Contact.cshtml
@*TODO: Create form for contacting RJ*@
@*TODO: Add in SendGrid to send email to RJ off of this page*@


@{
    ViewData["Title"] = "Contact";
}
<h1>@ViewData["Title"]</h1>

<p>For all pricing and booking questions, please fill out the form below. Include as much detail as possible. I look forward to hearing from you.</p>

<form method="post" action="ContactRequest.cshtml">
    <div class="row">
        <div class="col">
            <input type="text" class="form-control" placeholder="First Name" />
        </div>
        <div class="col">
            <input type="text" class="form-control" placeholder="Last Name" />
        </div>
    </div>
    <div class="form-group">
        <label for="EmailforContactForm">Email</label>
        <input type="email" class="form-control" id="form-email" placeholder="yourEmail@email.com" />
    </div>
    <div class="form-group">
        <label for="SubjectforContactForm">Subject</label>
        <input type="text" class="form-control" id="form-subject" />
    </div>
    <div class="form-group">
        <label for="MessageInfoForContact">Additional Information</label>
        <textarea class="form-control" id="form-message" cols="30" rows="10"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Submit Form</button>
</form>

SinderPhoto/Views/Home/ContactRequest.cshtml
@*TODO: Look up how to use logic apps with sendgrid*@

SinderPhoto/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@*TODO: Get highlight images from RJ*@
    <div class="text-center">
        <h1 class="display-4">Welcome</h1>
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block w-100" src="~/sample_pics/sample1.jpg" alt="First slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="~/sample_pics/sample2.jpg" alt="Second slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="~/sample_pics/sample3.jpg" alt="Third slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="~/sample_pics/sample4.jpg" alt="Forth slide">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>

SinderPhoto/Views/Home/Portfolio.cshtml


@{
    ViewData["Title"] = "Portfolio";
}
<h1>@ViewData["Title"]</h1>

<div class="container">
    <div class="row">
        <div class="col" id="landscapeImageLink">
            <a asp-controller="Album" asp-action="Landscapes">
                <label>Landscapes</label>
                <img class="d-block w-100" src="~/sample_pics/sample3.jpg" alt="Landscape Link">
            </a>
        </div>
        <div class="col" id="realEstateImageLink">
            <a asp-controller="Album" asp-action="RealEstate">
                <label>Real Estate</label>
                <img class="d-block w-100" src="~/sample_pics/sample2.jpg" alt="Real Estate Link">
            </a>

        </div>
    </div>
    <div class="row">
        <div class="col" id="portraitImageLink">
            <a asp-controller="Album" asp-action="Portraits">
                <label>Portraits</label>
                <img class="d-block w-100" src="~/sample_pics/sample1.jpg" alt="Portrait Link">
            </a>
        </div>
    </div>
</div>

SinderPhoto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!--TODO: Get Logo from RJ-->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://code.jquery.com/jquery-1.12.3.min.js" integrity="sha256-aaODHAgvwQW1bFOGXMeX+pC4PZIPsvn2h1sArYOhgXQ=" crossorigin="anonymous"></script>
    <script src="../../wwwroot/js/site.js"></script>
    <title>@ViewData["Title"] - Snider Photography</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img class="img-thumbnail w-25 h-25 float-left" src="~/Logo.jpg" /> </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <div class="row">
            <div class="col-4" id="sidebar">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle justify-content-end" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Portfolio
                        </a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" asp-controller="Home" asp-action="Portfolio">Portfolio Home</a>
                            <a class="dropdown-item" asp-controller="Album" asp-action="Landscapes">Landscapes</a>
                            <a class="dropdown-item" asp-controller="Album" asp-action="RealEstate">Real Estate</a>
                            <a class="dropdown-item" asp-controller="Album" asp-action="Portraits">Portraits</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
            <main role="main" class=" col-8 pb-3">
                @RenderBody()
            </main>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Snider Photography - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>